apiVersion: v1
kind: Pod                    
metadata:
  name: my-pod-service
  labels:
    app: my-app          
    type: front-end         
spec:
  containers:             
    - name: my-nginx      
      image: nginx 
    
