apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
  labels:
    app: my-replica-app
    type: front-end
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-replica-app
      type: front-end
  template:
    metadata:
      labels:
        app: my-replica-app
        type: front-end
    spec:
      containers:
        - name: mynginx
          image: nginx
